Vagrant.configure("2") do |config|
  config.vm.box = "centos7-tp4.box"

  ## Les 3 lignes suivantes permettent d'éviter certains bugs et/ou d'accélérer le déploiement. Gardez-les tout le temps sauf contre-indications.
  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false
 
  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

   # Config de la VM gitea
  config.vm.define "node1gitea" do |node1gitea|
    node1gitea.vm.network "private_network", ip: "192.168.56.11"
    node1gitea.vm.hostname = "node1.tp4.gitea"
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    config.vm.provision "shell",
      path: "/home/lemalgache/monrepo/tp4/scripts/node1.gitea.sh"
    end
  end

# Config de la VM 2
#  config.vm.define "node2" do |node2|
#    node2.vm.network "private_network", ip: "192.168.56.12"
#    node2.vm.hostname = "node2.tp2.b2"
#    config.vm.provider "virtualbox" do |vb|
#      vb.customize ["modifyvm", :id, "--memory", "512"]
#    end
#    config.vm.provision "shell",
#      path: "/home/lemalgache/vagrant/script2.sh"
#    end


