Vagrant.configure("2") do |config|
  config.vm.box = "centos7-tp4.box"

  ## Les 3 lignes suivantes permettent d'éviter certains bugs et/ou d'accélérer le déploiement. Gardez-les tout le temps sauf contre-indications.
  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config de la VM gitea
  config.vm.define "node1gitea" do |node1gitea|
    node1gitea.vm.network "private_network", ip: "192.168.56.11"
    node1gitea.vm.hostname = "node1.tp4.gitea"
    node1gitea.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    config.vm.provision "shell",
      path: "/home/lemalgache/monrepo/tp4/scripts/node1.gitea.sh"
  end

  # Config de la VM MariaDB
  config.vm.define "node2bdd" do |node2bdd|
    node2bdd.vm.network "private_network", ip: "192.168.56.12"
    node2bdd.vm.hostname = "node2.tp4.bdd"
    node2bdd.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    config.vm.provision "shell",
      path: "/home/lemalgache/monrepo/tp4/scripts/node2.bdd.sh"
  end

  # Config de la VM NGINX
  config.vm.define "node3nginx" do |node3nginx|
    node3nginx.vm.network "private_network", ip: "192.168.56.13"
    node3nginx.vm.hostname = "node3.tp4.nginx"
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    node3nginx.vm.provision "shell",
      path: "/home/lemalgache/monrepo/tp4/scripts/node3.nginx.sh"
  end

end
